import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildAdRegistryFromCsv } from '../js/helpers/buildAdRegistry.js';
import { buildWorkplacesFromAdRegistry } from '../js/helpers/seedWorkplacesFromAd.js';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

function readCsvFile(fileName) {
  return fs.readFileSync(path.join(root, fileName), 'utf8').replace(/^\uFEFF/, '');
}

const registry = buildAdRegistryFromCsv(readCsvFile('employees.csv'), readCsvFile('computers.csv'));

registry.source = 'Bundled from employees.csv and computers.csv';

const jsonPath = path.join(root, 'data', 'ad-sync.json');
fs.mkdirSync(path.dirname(jsonPath), { recursive: true });
fs.writeFileSync(jsonPath, `${JSON.stringify(registry, null, 2)}\n`, 'utf8');

const bundlePath = path.join(root, 'js', 'data', 'adSyncBundle.js');
fs.writeFileSync(
  bundlePath,
  `/** Generated by scripts/build-ad-sync.mjs — do not edit by hand */\nexport const AD_SYNC_VERSION = ${JSON.stringify(registry.syncedAt)};\nexport const bundledAdRegistry = ${JSON.stringify(registry)};\n`,
  'utf8'
);

const workplaces = buildWorkplacesFromAdRegistry(registry);

const workplacesPath = path.join(root, 'js', 'data', 'workplacesSeed.js');
fs.writeFileSync(
  workplacesPath,
  `/** Generated by scripts/build-ad-sync.mjs — do not edit by hand */\nexport const AD_WORKPLACES_VERSION = ${JSON.stringify(registry.syncedAt)};\nexport const workplacesFromAd = ${JSON.stringify(workplaces, null, 2)};\n`,
  'utf8'
);

console.log(`employees: ${registry.employees.length}`);
console.log(`computers: ${registry.computers.length}`);
console.log(`workstations (WSS): ${registry.workstations.length}`);
console.log(`workplaces seeded: ${workplaces.length}`);
console.log(`written: ${jsonPath}`);
console.log(`written: ${bundlePath}`);
console.log(`written: ${workplacesPath}`);
